### ISSUE TITLE
Bug: 0 is not considered a valid number for {num1..num2}

### ISSUE THREAD

**Issue by uap-universe** [editorconfig/editorconfig-core-c#102]
https://github.com/editorconfig/editorconfig-core-c/blob/c32b33d8a631a60f4294d2ad7f91c9faedaa3b1c/src/lib/ec_glob.c#L377-L379

This does not only discard numbers like "010", but also the "0" itself.

That means, the following pattern

```
*.orig.{0..9}
```
does not match the file

```
data.txt.orig.0
```

**Comment by greut** [comment]
You're looking at a specific implementation here, I sort of agree that the above pattern should be part of the test suite: https://github.com/editorconfig/editorconfig-core-test/blob/master/glob/braces.in#L65-L67

**Comment by cxw42** [comment]
Indeed, the spec says
> `{num1..num2}`
> 
> any integer numbers between num1 and num2, where num1 and num2 can be either positive or negative

which would imply zero should be allowed.

I am closing this in favor of the spec issue at https://github.com/editorconfig/editorconfig/issues/371 .  Once that issue is resolved, we will update the core tests and the cores will all need to be updated accordingly.
