### ISSUE TITLE
Shared Library Doesn't Exit Properly

### ISSUE THREAD

**Issue by barracks510** [editorconfig/editorconfig-core-c#12]
In the terms of Fedora's RPM Packaging checker:
> This library package calls exit() or _exit(), probably in a non-fork()
context. Doing so from a library is strongly discouraged - when a library
function calls exit(), it prevents the calling program from handling the
error, reporting it to the user, closing files properly, and cleaning up any
state that the program has. It is preferred for the library to return an
actual error code and let the calling program decide how to handle the
situation.

**Comment by xuhdev** [comment]
Fixed in a809fbd28da52af2516702fd0357a8328fe489c6
