### ISSUE TITLE
Typo in editorconfig_handle.c

### ISSUE THREAD

**Issue by slaf66** [editorconfig/editorconfig-core-c#17]
Use of 'minor' instead of 'patch' in:
    if (patch >= 0)
((struct editorconfig_handle*)h)->ver.patch = minor;

We fix this in our gnome-builder copy:

https://git.gnome.org/browse/gnome-builder/commit/?id=20d6603f64d603d45736e287f556b54498781162

**Comment by xuhdev** [comment]
Thanks, fixed now!
