### ISSUE TITLE
Be careful with indent_char for multiline strings

### ISSUE THREAD

**Issue by mcandre** [editorconfig/editorconfig-core-c#21]
`indent_char` has some false positives for multiline strings, when the multiline string content happens to misalign with the overall file indentation settings. For example, this can happen with (ba)sh scripts.

**Comment by jedmao** [comment]
Can you be more specific. This is the first I'm hearing of an `indent_char` setting for EditorConfig, so I'm not sure what you're talking about.

**Comment by craigbarnes** [comment]
@mcandre Any further info on this? The symbol `indent_char` doesn't seem to appear in this project at all.

**Comment by xuhdev** [comment]
It's been two years and no response. Closing now. Feel free to comment if you would like to discuss further.
