### ISSUE TITLE
editorconfig-core doesn't like square brackets in the parent folder name

### ISSUE THREAD

**Issue by tico-tico** [editorconfig/editorconfig-core-c#23]
followup of https://github.com/editorconfig/editorconfig/issues/310
easy to reproduce: put the parent folder name in square brackets and you'll break the lib.

for instance:
`editorconfig.exe c:\1\1.cpp` works
`editorconfig.exe c:\[1]\1.cpp` is silent
`editorconfig.exe c:\1]\1.cpp` works
`editorconfig.exe c:\1[\1.cpp` crashes

**Comment by xuhdev** [comment]
I can reproduce this bug. Will fix this.

**Comment by xuhdev** [comment]
I'll push the fix before the end of this week.

**Comment by xuhdev** [comment]
Please test again. Thank you!

**Comment by xuhdev** [comment]
Now this case should also be handled. Please test. Thanks!
