### ISSUE TITLE
Meson build support

### ISSUE THREAD

**Issue by TingPing** [editorconfig/editorconfig-core-c#24]
[Meson](http://mesonbuild.com) is an alternative build system and I wanted to know if you would accept a PR that adds support for it. The main reason this is wanted is because it supports 'subprojects' so other projects can easily bundle this library.

**Comment by xuhdev** [comment]
Thanks for your proposal. Does the Meson support still use CMake as the build system for this project itself, or the whole CMake thing has to be replaced? The testing cases are now built on top of CMake and are used by many other EditorConfig projects. Changing that seems not quite hazard.

**Comment by TingPing** [comment]
No it is a separate build system, it does not require removal of CMake though.

**Comment by xuhdev** [comment]
Can it make use of CMake though? I think it would be annoying if we have to change two build system settings if something changes in the building process.

**Comment by TingPing** [comment]
No it cannot. From what I can tell this projects build files are fairly static with the last noteworthy changes being 3 years ago. A project I contribute to would be using these build definitions and are constantly ran through CI where I would of course be willing to fix any build related issues.

**Comment by xuhdev** [comment]
Yes, I agree with you that the build is rather static. You now have me on that. But I'm still not quite convinced by your motivation: What is the advantage of Meson over CMake in terms of "subproject"? It looks like CMake can also support subproject.

**Comment by xuhdev** [comment]
As long as you can convince us on the motivation, I think we can accept a PR for Meson support.

**Comment by TingPing** [comment]
Well its as simple as our project uses meson so our subprojects would have to be in meson. This is just a would be nice on our end for it to be upstream and if needed we can keep maintaining it out of tree.

**Comment by TingPing** [comment]
After some thought I think it will be fine to not impose this on you.
