### ISSUE TITLE
Treat "none" value for indent_style as disabling this check

### ISSUE THREAD

**Issue by mcandre** [editorconfig/editorconfig-core-c#26]
Lisp code often indents better with the dynamic SLIME style than a fixed width indent. Could editorconfig-core-c help check Lisp code better by treating "none" values as disabling the `indent_style` check. Some other EditorConfig do this, with:

```
[{*.lisp,*.lsp,*.scm,*.el,*.rkt,*.abcl,*.ccl,*.clisp,*.ecl,*.sbcl,.eclrc,.sbclrc,*.m,*.mm}]
indent_size = none
```

**Comment by xuhdev** [comment]
This should be output in the core library, as anything not defined in the specification is reserved for extensions by editors. This is really an issue of editor support. In practice, editors treat undefined values as not specified.
