### ISSUE TITLE
Windows x64 build

### ISSUE THREAD

**Issue by ViceIce** [editorconfig/editorconfig-core-c#28]
Hi,

I'm trying to build editorconfig/editorconfig-notepad-plus-plus#9 for x64.
Which build options should i set to build pcre?

Regards
Michael

**Comment by xuhdev** [comment]
I used to build the static pcre library using the MT option. And I think this should really belong to an issue in the Notepad++ plugin repository. What do you think?

**Comment by ViceIce** [comment]
OK, I linked the npp issue.

I would like to be able to test the x64 build.

For MT option i created a patch:
https://gist.github.com/ViceIce/34a3ec7f1c433688dcc09c0fc797df07

Sofar one test fails:

```        Start  89: utf_8_char
 89/179 Test  #89: utf_8_char ................................***Failed  Required regular expression not found.Regex=[^key=value[


]*$
]  0.04 sec
```

**Comment by xuhdev** [comment]
@ViceIce Hmm, it looks a bit strange... Would you mind giving updates in the npp issue instead here? I think people who are interested in this build process are there not here.

**Comment by xuhdev** [comment]
I'm sorry, please continue updating here. I forgot you are actually building this C library.

**Comment by ViceIce** [comment]
I think it is helpful for others to providfe a 64bits build of this library too.
Then others don't hav to build all themself.

**Comment by xuhdev** [comment]
I just looked up what I've done before. I think I used to build with the `MD` option, and had to point out which VC dist package to install. Therefore, if the `MD` option works, it should be an excellent work to write down the build process of this library on Windows.

**Comment by ViceIce** [comment]
With the patch obove it will build with the `MT` option and no VC dist is required. 

To create x64 files i use:
 `cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX="$PREFIX" -DPCRE_BUILD_PCRECPP=OFF -DPCRE_BUILD_PCREGREP=OFF -DPCRE_BUILD_TESTS=OFF "$SRC"`

I'm using an out of source build. 😃

**Comment by xuhdev** [comment]
Great! That would be even better!

**Comment by ViceIce** [comment]
pcre 8.41 has a new flag `PCRE_STATIC_RUNTIME` for compiling with `MT` 😃

**Comment by xuhdev** [comment]
Awesome! Would you creating a PR for this repo, that builds the library with and without static pcre?

**Comment by ViceIce** [comment]
If i compile with md, i got linker errors for `editorconfig.dll`:

```
ec_glob.obj : error LNK2019: unresolved external symbol __imp_pcre_compile referenced in function ec_glob
```

**Comment by ViceIce** [comment]
I'm now able to compile, but all tests are failing.

**Comment by ViceIce** [comment]
Ok, build is working now. Only the `utf_8_char` test is failing.

**Comment by ppalaga** [comment]
`utf_8_char` also fails when we run it on Window against our Java parser lib. Our debug output seems to suggest that the the ctest process is using an improper encoding when passing the Asian file path to our executable. This is the relevant section of `Testing/Temporary/LastTest.log`. Note that ctest lists the command properly with `中文.txt`, but our executable sees `??.txt`. Is there any cmake option to fix this?

```
89/179 Testing: utf_8_char
89/179 Test: utf_8_char
Command: "C:/Program Files/Java/jdk1.7.0/bin/java.exe" "-cp" "C:/projects/ec4j/core/target/org.eclipse.ec4j.core.jar" "org.eclipse.ec4j.core.cli.Cli" "-f" "utf8char.in" "C:/projects/ec4j/core/editorconfig-core-test/glob/中文.txt"
Directory: C:/projects/ec4j/core/editorconfig-core-test/glob
"utf_8_char" start time: Nov 12 18:48 Coordinated Universal Time
Output:
----------------------------------------------------------
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <?> at index 50: C:/projects/ec4j/core/editorconfig-core-test/glob/??.txt
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.eclipse.ec4j.core.cli.Cli.main(Cli.java:117)
<end of output>
Test time =   0.09 sec
----------------------------------------------------------
Test Fail Reason:
Required regular expression not found.Regex=[^key=value[ 	
]*$
]
"utf_8_char" end time: Nov 12 18:48 Coordinated Universal Time
"utf_8_char" time elapsed: 00:00:00
----------------------------------------------------------

```
