### ISSUE TITLE
Option to use POSIX regex instead of PCRE

### ISSUE THREAD

**Issue by craigbarnes** [editorconfig/editorconfig-core-c#49]
Currently `src/lib/ec_glob.c` depends on PCRE, which I guess is for cross-platform compat purposes. However, it's quite a large dependency for something that can also be done using `regex.h` on Linux/OS X/*BSD. Would you be open to a pull request that adds a build-time option to use the POSIX regex API instead of PCRE?

**Comment by ffes** [comment]
I am **definitely not** an expert when it comes to regular expression, but how does the syntax of POSIX regex differ from that of PRCE?

In other words, it this proposed change going to break anybody's `.editorconfig` file they have in their repo because a regex don't work anymore?

When I look at https://www.regular-expressions.info/refbasic.html and choose "PRCE2" and "POSIX BRE" I see for instance that a `|` is not supported in POSIX. Looking at other pages on the same site with the same flavors chosen I see a lot of differences.

**Comment by craigbarnes** [comment]
> but how does the syntax of POSIX regex differ from that of PRCE

It lacks a few features that are Perl-specific extensions, but the code in `ec_glob.c` shouldn't actually need anything besides the basic POSIX features.

> In other words, it this proposed change going to break anybody's `.editorconfig` file they have in their repo because a regex don't work anymore?

Not if done correctly, no.`.editorconfig` files don't use regex patterns directly, they use a custom format similar to the ones used by POSIX `glob()` and `fnmatch()`. From the git history, it seems like the code _used to_ rely on an actual `fnmatch()` implementation (taken from FreeBSD), but the pattern format was later extended (beyond the capabilities of `fnmatch()`) and the code was changed to instead convert the patterns to regex (using PCRE for matching -- purely as an implementation detail).

> and "POSIX BRE" I see for instance that a `|` is not supported in POSIX

POSIX BRE is considered a legacy format -- only kept in the spec for historical compatibility. All modern POSIX platforms also support the extended format (ERE), which supports the `|` operator.

**Comment by ffes** [comment]
Thanks for the clarification :+1:

I think one of the maintainers of this repo can answer your original question :wink:

**Comment by xuhdev** [comment]
What is the application in your case that makes installing PCRE so burdensome?

**Comment by craigbarnes** [comment]
> What is the application in your case that makes installing PCRE so burdensome?

My use case is (optional) static linking with musl libc. libpcre is about 450K of object code, which would triple the size of the binary I'm trying to add editorconfig support to.

**Comment by craigbarnes** [comment]
I've done this in a separate [implementation](https://github.com/craigbarnes/dte/tree/master/src/editorconfig), instead of trying to shoehorn it into editorconfig-core-c. I guess no one else really cares about using POSIX regex, so I'm going to just close the issue.
