### ISSUE TITLE
Glob: Handling of `?`

### ISSUE THREAD

**Issue by rakus** [editorconfig/editorconfig-core-c#58]
The glob wildcard `?` is translated to a `.` in a regular expression.

With this, the glob expression `a?b.c` matches `a_b.c` but also `a/b.c`.

I think `?` should be translated to `[^/]`.

**Comment by rakus** [comment]
Same for editorconfig-core-java and editorconfig-core-py.

editorconfig-core-javascript translates `?` to `[^/]`.

**Comment by xuhdev** [comment]
I think you are right. We should also add a test for this.

**Comment by craigbarnes** [comment]
Doing this seems like it would be a divergence from `fnmatch()`/`glob()` behaviour.

**Comment by rakus** [comment]
Yes, a test would be good. You might also consider some unit-tests. I added some to my fork. See [here](https://github.com/rakus/editorconfig-core-c/tree/new-glob2re/src/unit-test).

**Comment by xuhdev** [comment]
@rakus Could you make a PR for the unit test?

**Comment by xuhdev** [comment]
Oops, sorry. Testing for regex probably should go to editorconfig-core-test.

**Comment by rakus** [comment]
@xuhdev I'm not sure, the implementations might create different regex. The current c and python implementations PCRE, but Java uses its own regex syntax. Don't know about Javascript.

I think the unit tests have to be implementation specific.

**Comment by craigbarnes** [comment]
> I think the unit tests have to be implementation specific.

Not if you just check the matching behaviour instead of the contents of the generated regex.
