### ISSUE TITLE
Path to using a system copy of inih?

### ISSUE THREAD

**Issue by musicinmybrain** [editorconfig/editorconfig-core-c#91]
Under Fedora Linux’s [guidelines for bundled libraries](https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling), we’re required to contact upstreams publicly about a path to supporting external or system copies of any bundled librares.

I expect that this will not be possible with [inih](https://github.com/benhoyt/inih) because, if nothing else, there are hard-coded size limits that differ between the upstream implementation and the forked version in `editorconfig-core-c`. However, a quick opinion on this would still be appreciated.

**Comment by xuhdev** [comment]
Correct, our version has diverged from inih and I don't think we can use a system wide inih library.

**Comment by musicinmybrain** [comment]
Thank you!
